flyway:
  enabled: false
  locations: classpath:/db/migation
spring:
  datasource:
    name: pps_hup
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pps_hup
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
  application:
    name: basic-server
server:
  port: 8002